import { slugify } from './path-utils.js';

export function composerJson(metadata) {
  const slug = slugify(metadata.textDomain ?? metadata.name);
  return `${JSON.stringify({
    name: `local/${slug}`,
    description: metadata.description ?? `Test harness for ${metadata.name}`,
    type: 'wordpress-plugin',
    license: metadata.license ?? 'GPL-2.0-or-later',
    require: {},
    requireDev: {
      'phpunit/phpunit': '^9.6',
      'wp-coding-standards/wpcs': '^3.0',
      'dealerdirect/phpcodesniffer-composer-installer': '^1.0'
    },
    scripts: {
      test: 'phpunit',
      lint: 'phpcs'
    }
  }, null, 2)}\n`;
}

export function phpunitXml(metadata) {
  return `<?xml version="1.0"?>
<phpunit bootstrap="tests/bootstrap.php" colors="true">
  <testsuites>
    <testsuite name="${escapeXml(metadata.name)} tests">
      <directory suffix="Test.php">tests</directory>
    </testsuite>
  </testsuites>
</phpunit>
`;
}

export function phpcsXml(metadata) {
  return `<?xml version="1.0"?>
<ruleset name="${escapeXml(metadata.name)}">
  <description>WordPress Coding Standards for ${escapeXml(metadata.name)}.</description>
  <rule ref="WordPress" />
  <file>.</file>
  <exclude-pattern>vendor/*</exclude-pattern>
</ruleset>
`;
}

export function bootstrapPhp(metadata, mainFile) {
  return `<?php
/**
 * PHPUnit bootstrap for ${metadata.name}.
 * Generated by plugtestkit; review paths before committing to production.
 */

$_tests_dir = getenv('WP_TESTS_DIR') ?: '/tmp/wordpress-tests-lib';

if (! file_exists($_tests_dir . '/includes/functions.php')) {
    echo "Could not find WordPress test suite. Set WP_TESTS_DIR.\\n";
    exit(1);
}

require_once $_tests_dir . '/includes/functions.php';

tests_add_filter('muplugins_loaded', function (): void {
    require dirname(__DIR__) . '/${escapePhpSingleQuoted(mainFile)}';
});

require $_tests_dir . '/includes/bootstrap.php';
`;
}

export function exampleTestPhp(metadata) {
  return `<?php
class ${className(metadata.name)}SmokeTest extends WP_UnitTestCase {
    public function test_plugin_loaded(): void {
        $this->assertTrue(function_exists('do_action'));
    }
}
`;
}

export function githubActionsCi(matrix) {
  return `name: WordPress Plugin Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      fail-fast: false
      matrix:
        php: [${matrix.php.map((v) => `'${v}'`).join(', ')}]
        wordpress: [${matrix.wordpress.map((v) => `'${v}'`).join(', ')}]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: \${{ matrix.php }}
          tools: composer
      - run: composer install
      - name: Install WordPress test suite
        env:
          WP_VERSION: \${{ matrix.wordpress }}
          DB_PORT: \${{ job.services.mysql.ports[3306] }}
        run: |
          curl --fail --silent --show-error --location \
            --output /tmp/install-wp-tests.sh \
            https://raw.githubusercontent.com/wp-cli/scaffold-command/main/templates/install-wp-tests.sh
          bash /tmp/install-wp-tests.sh wordpress_test root '' "127.0.0.1:\${DB_PORT}" "\${WP_VERSION}"
      - run: composer test
`;
}

function className(name) {
  const readableName = String(name).replace(/[^A-Za-z0-9]+/g, ' ').trim().split(/\s+/).map((part) => part[0]?.toUpperCase() + part.slice(1)).join('') || 'Plugin';
  return /^[A-Za-z_]/.test(readableName) ? readableName : `Plugin${readableName}`;
}

function escapeXml(value) {
  return String(value).replace(/[<>&'"]/g, (char) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '\'': '&apos;', '"': '&quot;' }[char]));
}

function escapePhpSingleQuoted(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
